export const CryptoSymbol = {
  ETH: 'ETHUSDT',
  SOL: 'SOLUSDT',
  BNB: 'BNBUSDT',
  XRP: 'XRPUSDT',
  ADA: 'ADAUSDT',
  AVAX: 'AVAXUSDT',
  LINK: 'LINKUSDT',
  DOT: 'DOTUSDT',
  LTC: 'LTCUSDT',
  ATOM: 'ATOMUSDT',
  NEAR: 'NEARUSDT',
  APT: 'APTUSDT',
  ARB: 'ARBUSDT',
  OPU: 'OPUSDT',
  INJ: 'INJUSDT',
  SUI: 'SUIUSDT',
  WIF: 'WIFUSDT',
  UNI: 'UNIUSDT',
  AAVE: 'AAVEUSDT',
  TRX: 'TRXUSDT',
  ICP: 'ICPUSDT',
  ALGO: 'ALGOUSDT',
} as const
export type CryptoSymbol = (typeof CryptoSymbol)[keyof typeof CryptoSymbol]
